{
  "openapi": "3.0.1",
  "info": {
    "title": "Módulo predeterminado",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/apiEstudiantes/Estudiantes": {
      "get": {
        "summary": "Obtener Todos los Estudiantes",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": [
                  {
                    "id": 1,
                    "name": "Adonis",
                    "lastName": "Lopez",
                    "age": 20,
                    "email": "adoni@example.com",
                    "career": "TSDS"
                  },
                  {
                    "id": 2,
                    "name": "Erika",
                    "lastName": "Lopez",
                    "age": 31,
                    "email": "Erika@example.com",
                    "career": "Pedagogia"
                  }
                ]
              }
            }
          }
        },
        "security": []
      },
      "post": {
        "summary": "Añadir Estudiante",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "dni": "1752195782",
                "name": "Adonis",
                "lastName": "Lopez",
                "age": 20,
                "email": "adonis.lopez@epn.edu.ec",
                "career": "TSDS"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": "Estudiante creado exitosamente"
              }
            }
          }
        },
        "security": []
      }
    },
    "/apiEstudiantes/Estudiantes/3": {
      "get": {
        "summary": "Obtener un estudiante por id",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "timestamp": "2026-01-21T20:19:22.244198",
                  "message": "Estudiante no encontrado con ID: 3",
                  "details": "uri=/apiEstudiantes/Estudiantes/3"
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/apiEstudiantes/Estudiantes/cedula/1752195782": {
      "get": {
        "summary": "Buscar Estudiante Por cedula",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "id": 2,
                  "dni": "1752195782",
                  "name": "Adonis",
                  "lastName": "Lopez",
                  "age": 20,
                  "email": "adonis.lopez@epn.edu.ec",
                  "career": "TSDS"
                }
              }
            }
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "responses": {},
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}